const carData = [
  {
    brand: "Toyota",
    models: [
      {
        name: "Corolla",
        year: 2021,
        isNew: true,
        price: 20000,
        currency: "USD",
        city: "Baku",
        image:
          "https://turbo.azstatic.com/uploads/f460x343/2024%2F11%2F19%2F21%2F15%2F01%2F3bfdce4c-f285-468c-8b7a-4d2646ee0c72%2F82570_03Jwy_e00fC2mfxpGD9upA.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Camry",
        year: 2020,
        isNew: false,
        price: 25000,
        currency: "USD",
        city: "Ganja",
        image:
          "https://turbo.azstatic.com/uploads/f460x343/2024%2F11%2F19%2F21%2F15%2F01%2F3bfdce4c-f285-468c-8b7a-4d2646ee0c72%2F82570_03Jwy_e00fC2mfxpGD9upA.jpg",
        bodyType: "Sedan",
      },
      {
        name: "RAV4",
        year: 2022,
        isNew: true,
        price: 35000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/rav42022.jpg",
        bodyType: "SUV",
      },
      {
        name: "Land Cruiser",
        year: 2018,
        isNew: false,
        price: 55000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/landcruiser2018.jpg",
        bodyType: "SUV",
      },
      {
        name: "Yaris",
        year: 2021,
        isNew: true,
        price: 15000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/yaris2021.jpg",
        bodyType: "Hatchback",
      },
    ],
  },
  {
    brand: "BMW",
    models: [
      {
        name: "X5",
        year: 2022,
        isNew: true,
        price: 70000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/x52022.jpg",
        bodyType: "SUV",
      },
      {
        name: "320i",
        year: 2020,
        isNew: false,
        price: 30000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/320i2020.jpg",
        bodyType: "Sedan",
      },
      {
        name: "M4",
        year: 2021,
        isNew: true,
        price: 80000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/m42021.jpg",
        bodyType: "Coupe",
      },
      {
        name: "X6",
        year: 2019,
        isNew: false,
        price: 65000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/x62019.jpg",
        bodyType: "SUV",
      },
      {
        name: "Z4",
        year: 2022,
        isNew: true,
        price: 45000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/z42022.jpg",
        bodyType: "Convertible",
      },
    ],
  },
  {
    brand: "Mercedes",
    models: [
      {
        name: "C-Class",
        year: 2021,
        isNew: true,
        price: 40000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/cclass2021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "E-Class",
        year: 2020,
        isNew: false,
        price: 45000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/eclass2020.jpg",
        bodyType: "Sedan",
      },
      {
        name: "GLE",
        year: 2022,
        isNew: true,
        price: 75000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/gle2022.jpg",
        bodyType: "SUV",
      },
      {
        name: "S-Class",
        year: 2021,
        isNew: true,
        price: 90000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/sclass2021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "A-Class",
        year: 2020,
        isNew: false,
        price: 35000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/aclass2020.jpg",
        bodyType: "Hatchback",
      },
    ],
  },
  {
    brand: "Audi",
    models: [
      {
        name: "A3",
        year: 2021,
        isNew: true,
        price: 25000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/a32021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "A4",
        year: 2020,
        isNew: false,
        price: 30000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/a42020.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Q7",
        year: 2022,
        isNew: true,
        price: 85000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/q72022.jpg",
        bodyType: "SUV",
      },
      {
        name: "Q5",
        year: 2021,
        isNew: true,
        price: 55000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/q52021.jpg",
        bodyType: "SUV",
      },
      {
        name: "TT",
        year: 2020,
        isNew: false,
        price: 45000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/tt2020.jpg",
        bodyType: "Coupe",
      },
    ],
  },
  {
    brand: "Ford",
    models: [
      {
        name: "Focus",
        year: 2021,
        isNew: true,
        price: 22000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/focus2021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Escape",
        year: 2020,
        isNew: false,
        price: 27000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/escape2020.jpg",
        bodyType: "SUV",
      },
      {
        name: "Mustang",
        year: 2022,
        isNew: true,
        price: 50000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/mustang2022.jpg",
        bodyType: "Coupe",
      },
      {
        name: "F-150",
        year: 2021,
        isNew: true,
        price: 35000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/f1502021.jpg",
        bodyType: "Truck",
      },
      {
        name: "Explorer",
        year: 2019,
        isNew: false,
        price: 40000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/explorer2019.jpg",
        bodyType: "SUV",
      },
    ],
  },
  {
    brand: "Honda",
    models: [
      {
        name: "Civic",
        year: 2022,
        isNew: true,
        price: 22000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/civic2022.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Accord",
        year: 2020,
        isNew: false,
        price: 27000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/accord2020.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Pilot",
        year: 2021,
        isNew: true,
        price: 45000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/pilot2021.jpg",
        bodyType: "SUV",
      },
      {
        name: "CR-V",
        year: 2022,
        isNew: true,
        price: 40000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/crv2022.jpg",
        bodyType: "SUV",
      },
      {
        name: "HR-V",
        year: 2019,
        isNew: false,
        price: 25000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/hrv2019.jpg",
        bodyType: "SUV",
      },
    ],
  },
  {
    brand: "Nissan",
    models: [
      {
        name: "Altima",
        year: 2021,
        isNew: true,
        price: 25000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/altima2021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Maxima",
        year: 2020,
        isNew: false,
        price: 30000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/maxima2020.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Murano",
        year: 2022,
        isNew: true,
        price: 55000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/murano2022.jpg",
        bodyType: "SUV",
      },
      {
        name: "Rogue",
        year: 2021,
        isNew: true,
        price: 32000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/rogue2021.jpg",
        bodyType: "SUV",
      },
      {
        name: "370Z",
        year: 2020,
        isNew: false,
        price: 40000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/370z2020.jpg",
        bodyType: "Coupe",
      },
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      {
        name: "Malibu",
        year: 2021,
        isNew: true,
        price: 23000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/malibu2021.jpg",
        bodyType: "Sedan",
      },
      {
        name: "Tahoe",
        year: 2020,
        isNew: false,
        price: 60000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/tahoe2020.jpg",
        bodyType: "SUV",
      },
      {
        name: "Silverado",
        year: 2022,
        isNew: true,
        price: 70000,
        currency: "USD",
        city: "Ganja",
        image: "https://linktotheimage.com/silverado2022.jpg",
        bodyType: "Truck",
      },
      {
        name: "Equinox",
        year: 2021,
        isNew: true,
        price: 35000,
        currency: "USD",
        city: "Baku",
        image: "https://linktotheimage.com/equinox2021.jpg",
        bodyType: "SUV",
      },
      {
        name: "Camaro",
        year: 2020,
        isNew: false,
        price: 45000,
        currency: "USD",
        city: "Sumqayit",
        image: "https://linktotheimage.com/camaro2020.jpg",
        bodyType: "Coupe",
      },
    ],
  },
];

console.log(carData);
